name: cs236605-tutorials
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch==1.0.1
  - torchvision==0.2.1
  - ipython
  - jupyter
  - jupyterlab
  - scipy
  - numpy
  - scikit-learn
  - pandas
  - cython
  - rise
  - numba
  - spacy
  - nltk
  - pip:
    - torchtext
      # spaCy en model
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
    - matplotlib~=3.0
    - keras
