name: cs236605-tutorials
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch>1.0.0
  - ipython
  - jupyter
  - jupyterlab
  - scipy
  - numpy
  - scikit-learn
  - pandas
  - cython
  - rise
  - numba
  - pip:
    - torchvision
    - matplotlib~=3.0
    - keras
