name: cs236605-tutorials
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - pytorch
  - ipython
  - jupyter
  - jupyterlab=0.35
  - scipy
  - numpy=1.15
  - scikit-learn
  - pandas
  - cython
  - rise
  - pip:
    - torchvision
    - matplotlib~=3.0
