name: cs236605-tutorials
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch==1.0.1
  - torchvision==0.2.1
  - cudatoolkit==9.0
  - matplotlib
  - ipython
  - jupyter
  - jupyterlab
  - scipy
  - numpy
  - scikit-learn
  - pandas
  - cython
  - rise
  - numba
  - spacy
  - nltk
  - ffmpeg>4.1
  - x264
  - tensorboardX
  - opencv
  - freetype>=2.10
  - pip
  - pip:
    - torchtext
    - tensorflow
    - tensorflow-tensorboard
      # spaCy en model
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
    - gym
    - 'gym[atari]'
