name: cs236605-tutorials
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - ipython
  - jupyter
  - jupyterlab=0.35
  - scipy
  - numpy=1.15
  - scikit-learn
  - pandas
  - cython
  - pip:
    - matplotlib~=3.0
