name: cs236781
channels:
  - defaults
  - conda-forge
  - pytorch
  - dglteam
dependencies:
  - python=3.8.6
  - pytorch=1.6.0
  - ipython
  - torchvision
  - torchtext
  - pillow
  - cudatoolkit
  - matplotlib
  - jupyter
  - jupyterlab
  - scipy
  - numpy
  - scikit-learn
  - pandas
  - cython
  - rise
  - numba
  - spacy
  - nltk
  - ffmpeg
  - opencv
  - freetype
  - dgl
  - graphviz
  - python-graphviz # needed for graphviz on windows
  - swig
  - gym
  - gym-atari
  - gym-box2d
  - pip
  - pip:
      # spaCy models
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
    - https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-2.3.0/de_core_news_sm-2.3.0.tar.gz
    - torchviz
